name: Run tests
on: [push, pull_request]

jobs:
  test-client:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python: [3.8, 3.9, "3.10", 3.12]
        extras: ["test", "test,queuable,sentry"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        working-directory: ./client
        run: |
          pip --version
          pip install --verbose .[${{ matrix.extras }}]
          python -m pytest --import-mode=importlib ./datalake/tests/
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test
        run: |
          make test-ingester test-api
